### ISSUE TITLE
Schedule First TOC Meeting

### ISSUE THREAD

**Issue by dlorenc** [cdfoundation/toc#1]
This is a tracking issue to schedule the first TOC meeting. We can do this over zoom, so we just need to pick a date and time people are available.

Chris said we should aim for one in about a month. I'll update this with some times soon and we can vote.

**Comment by caniszczyk** [comment]
I'd suggest shooting for something the last week of this month, I'll provide a zoom.

**Comment by dlorenc** [comment]
I setup a doodle here: https://doodle.com/poll/7kfkgsheg39rtmzn

Given we're GMT/PST I limited options to 8am,9am,10am Mon-Friday. 

cc @aglover @caniszczyk @kohsuke @jstrachan please vote soon!

**Comment by dlorenc** [comment]
Looks like @caniszczyk is the toughest to schedule around.  The 26th and 27th at 9 or 10 Pacific work for everyone else though. In the interest of expediency, let's go with 9am Pacific on the 26th.

**Comment by dlorenc** [comment]
Created a calendar of meetings here: https://calendar.google.com/calendar?cid=amJqM250cjJmdGZyMmRxZDNwMmppYjJsMWNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by kohsuke** [comment]
Thanks Dan for completing this, I think we can mark this ticket closed!

**Comment by caniszczyk** [comment]
thanks @dlorenc, let's all ensure all meeting minutes/agenda are consolidated in one doc moving forward: https://docs.google.com/document/d/1uBHar55fTInWF9Li4t0lyG3tTC8BRLU0FfBfsgk_Jrs/edit#
