### ISSUE TITLE
Add CD Events as Incubating project

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/toc#110]
Adding a placeholder for our roadmap. The Events SIG has defined a name for its CI/CD events standard (CD Events), and there are 2 ongoing adoptions already. It would be nice if we officially add it as Incubating project.

Prerequisites:

- [x] Project Brief and Logo - In progress - https://docs.google.com/document/d/1wJySvZFPetKTXEa_VD_gbUyDVnV6O272H-n__0FoG2E/edit?usp=sharing 
- [x] TOC Presentation
- [x] Voting
- [ ] Website update

**Comment by sbtaylor15** [comment]
See PR #136

**Comment by oleg-nenashev** [comment]
The proposal has been officially accepted on Dec 01, see https://lists.cd.foundation/g/cdf-toc/message/756 . The next step is to get the website and other CDF resources updated
