### ISSUE TITLE
Tekton Security Audit

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/toc#113]
Third-party security audit is a prerequisite for project graduation in the CDF (#112)

* TOC Sponsor: @afrittoli

**Comment by afrittoli** [comment]
Related foundation ticket https://github.com/cdfoundation/foundation/issues/257

**Comment by fdegir** [comment]
FYI - this should be pretty close to the completion.

**Comment by fdegir** [comment]
I believe this issue can be closed.

**Comment by oleg-nenashev** [comment]
Yes. FTR https://cd.foundation/blog/2022/08/26/tekton-security-review-completed/
