### ISSUE TITLE
Create a new project onboarding template

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/toc#115]
As discussed at one of the TOC meeting, we need to create a new project onboarding request template for the incubating projects that would fit the Lifecycle criteria.

* TOC Champion: @sbtaylor15

**Comment by sbtaylor15** [comment]
Template needs to include accounts that may need to be transferred or co-ownership added.

- Web Meeting Accounts - Zoom
- Meetup Accounts
- YouTube
- Twitter
- LinkedIn
- Facebook
- Domain Name
- Infrastructure accounts - AWS, Google, Azure
- Google Groups, Drive, Slides, Docs

**Comment by sbtaylor15** [comment]
Resolved in PR #132

**Comment by sbtaylor15** [comment]
Additional changes may be needed to match up with #135.  Closing this issue since it reflects the changes needed at this time.
