### ISSUE TITLE
Cleanup the CDF Landscape

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/toc#120]
The CDF Landscape is undergoing a cleanup.
Champion: @MarckK 

Please join the initiative, or find out how to get involved, through the links below!

Links:
* [CDF Landscape site](https://github.com/cdfoundation/cdf-landscape)
* [Let's (re)Consider Categories on CDF Landscape](https://github.com/cdfoundation/cdf-landscape/issues/175)
* [Suggested list of projects to add to landscape](https://github.com/cdfoundation/cdf-landscape/issues/123)
* [Project Board for adding additional projects to landscape](https://github.com/cdfoundation/cdf-landscape/projects/1)
* [Ensure all CDF Members represented](https://github.com/cdfoundation/cdf-landscape/issues/147)  -- Completed

**Comment by MarckK** [comment]
An initial cleanup of the CDF landscape was completed a number of months ago. 

Iterating on the landscape is an ongoing process and never finished. However, I was the primary person working on this and my focus has shifted considerably in the last few months.

As such, I suggest closing this issue for now and reopening when there is another champion for another iteration.
