### ISSUE TITLE
Proposed charter Brazilian Location SIG

### ISSUE THREAD

**Issue by brbernardo** [cdfoundation/toc#141]
## Brief overview

Brazilian Location SIG

## Proposed meeting schedule

Biweekly meeting, BRT time zone.

## Outcomes

Organize and engage the Brazilian community cd.foundation.
Promote local events
Ambassador of local community values.

## List of initial members

Guto Carvalho - @gutocarvalho
Luiz Bernardo - @brbernardo
Matheus Paes Pereira - @MatheusPaes

## SIG Onboarding Checklist

This is the checklist for new SIGs

- [ ] Create GitHub repo
- [ ] Create GitHub team for the sig (cochairs should manage the team)
- [x] Create slack channel (or rename existing channel to reflect sig name)
     - [#sig-brasil](https://cdeliveryfdn.slack.com/archives/C0331JSL37F)
- [ ] Create groups.io mailing list
- [ ] SIG co-chairs to get access to CDF calendar to modify events
- [ ] Create SIG playlist on Youtube
- [ ] Announcement blog post/press release
- [ ] Recommend scheduling a podcast: https://cd.foundation/podcast/

**Comment by afrittoli** [comment]
Thanks @brbernardo!! 🎉 

Could you add the company affiliation for the initial SIG members? One of the requirements to form a SIG is that "There should be at least 3 different companies represented".

https://github.com/cdfoundation/toc/blob/master/GROUPS.md#sigs

**Comment by brbernardo** [comment]
Hi, @afrittoli 

Add the company affiliation for the initial SIG members

Guto Carvalho - [DNSFilter](https://github.com/DNSFilter)
Luiz Bernardo - [DB1 Global Software](https://github.com/db1group)
Matheus Paes Pereira - [PicPay](https://github.com/PicPay)

**Comment by oleg-nenashev** [comment]
I am generally +1 for this SIG. I would rather call it the "CDF Brasil Chapter" though so that we do not use the "SIG" framework which is not necessary in this case.

For a chapter we could provide landing on http://community.cd.foundation/ , GitHub repo, a Slack channel(s), and all other resources provided to SIGs

**Comment by bajpaigarima** [comment]
@Matheus Paes - We should discuss it within the CDF Ambassadors - events sub-group. We have the CDF Kanban https://github.com/cdfoundation/community-ambassador-program/projects/1

**Comment by sbtaylor15** [comment]
> I am generally +1 for this SIG. I would rather call it the "CDF Brasil Chapter" though so that we do not use the "SIG" framework which is not necessary in this case.
> 
> For a chapter we could provide landing on http://community.cd.foundation/ , GitHub repo, a Slack channel(s), and all other resources provided to SIGs

I agree that we should call it "CDF Brasil Chapter".  +1

**Comment by MatheusPaes** [comment]
> @matheus Paes - We should discuss it within the CDF Ambassadors - events sub-group. We have the CDF Kanban https://github.com/cdfoundation/community-ambassador-program/projects/1

Agree with you, I'll add a card to discuss with the CDF ambassadors. Thanks for the suggestion!

**Comment by brbernardo** [comment]
Hi, thank you very much for all your thoughts.
I will close this issue

**Comment by oleg-nenashev** [comment]
I created a Slack channel where it can be discussed: `#cdf-brazil`
