### ISSUE TITLE
Access to Jenkins X CDF GCP infra billing account

### ISSUE THREAD

**Issue by ankitm123** [cdfoundation/toc#147]
It would be great if I (and the other Jenkins X maintainers) can have access to the billing account for JX infrastructure. I want to explore ways to keep our costs low, and want to check how much we have been spending each month on our infrastructure.

When I try to access the billing account, I get this message:
```
You don’t have permission to view costs for project “jenkinsxio”
```
and
```
You don’t have permission to view costs for project “jenkins-x-bdd”
```

**Comment by zestyroxy** [comment]
Please email Michelle Martineau, @ankitm123 I'll send you her email.

**Comment by ankitm123** [comment]
I have access now. Closing this.
