### ISSUE TITLE
Request to present Screwdriver (open source build platform for CD)

### ISSUE THREAD

**Issue by Rosalie** [cdfoundation/toc#16]
Hi CD Foundation Team!

I'm on the open source team at Verizon Media and work closely with the creators of Screwdriver (screwdriver.cd), an open source build platform designed for continuous delivery. Screwdriver was created and open sourced by Yahoo (now Verizon Media).

I'd love to express interest in the Screwdriver team presenting the project to you and answering any questions, during your July meeting.

Thanks!

**Comment by caniszczyk** [comment]
RFC @cdfoundation/toc and @danlopez00 to get on the agenda and help them prepare a project proposal

**Comment by caniszczyk** [comment]
they presented and now have a proposal for the @cdfoundation/toc to review

**Comment by caniszczyk** [comment]
https://github.com/cdfoundation/toc/pull/22
