### ISSUE TITLE
CDF Charter Updates - CDF TOC Co-chair

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/toc#161]
As discussed during the TOC Meeting on October 11, we prepared updates to the CDF Charter to update [the clause 7.f](https://github.com/cdfoundation/charter/blob/main/CHARTER.md#7-technical-oversight-committee-toc) which is where CDF TOC Chair is documented.

Here is what is documented on the charter currently

> The TOC representatives will elect a chair to preside over meetings, ensure minutes are taken and drive the TOC agenda with input from the TOC representatives, who will also serve as the TOC Representative. 

Here is the proposed update

> The TOC Co-chairs shall be elected to a one-year term with a maximum of two terms allowed. The General Manager may call a special election as needed. TOC co-chairs will be nominated from within the CDF TOC, and elected by the members of the CDF TOC voting members.

Could you please provide your feedback on the proposed update?

In parallel to this, we are working with the LF Legal to get redlined version of the charter to be presented to CDF GB for approval.
Depending on when the LF Legal completes their work and when CDF GB approves the updated charter, we may call for a special election to elect CDF TOC Co-chair.

**Comment by afrittoli** [comment]
Thanks @fdegir for this. 

This is a fine proposal, I'm however worried that it might lead to deadlock situations in case one of the two co-chairs was not available for any reason. 

A deputy chair setup might provide a similar advantage, while ensuring that if the chair is not available for any reason, the deputy may take over with full authority.

**Comment by oleg-nenashev** [comment]
I agree with @afrittoli . I would explicitly document that in the TOC Charter that All TOC members should get all necessary permissions to run the meetings and manage the roadmap and the repositories. I see no reason to have any TOC Chair differentiation there

@fdegir Would the rest of the charter be updated accordingly, e.g. the Governance Board so that both Co-chairs are on it?

**Comment by fdegir** [comment]
> I would explicitly document that in the TOC Charter that All TOC members should get all necessary permissions to run the meetings and manage the roadmap and the repositories. I see no reason to have any TOC Chair differentiation there

I believe this is already the case.
The TOC Member with Bevy accounts can control the meetings.
They are also added to the @cdfoundation/toc team and should have the necessary permissions to work with the GitHub repo.

> @fdegir Would the rest of the charter be updated accordingly, e.g. the Governance Board so that both Co-chairs are on it?

If I understand @afrittoli's comment correctly, having 2 co-chairs could result in deadlock situations so the discussion is around having a deputy chair in addition to the TOC Chair. In this case, yes, the chair and deputy chair can be alternates in the GB.

**Comment by afrittoli** [comment]
As discussed in the TOC meeting on January 17, 2023, the current proposal is to have a TOC vice chair, someone who attends the TOC meetings on a regular basis and who can stand in as chair in case of the absence of the chair.

**Comment by afrittoli** [comment]
Thanks @sbtaylor15. 

I agree the name doesn't matter too much. 
That said, eve if I'm not native speaker, it feels to me like deputy is more appropriate than vice.

**Comment by jithine** [comment]
I wonder if the size of TOC warrants the need for vice/deputy chair. Also what action enables/authorizes vice chair to make decisions ? Should it be explicit delegation on chair's part.

**Comment by afrittoli** [comment]
> I wonder if the size of TOC warrants the need for vice/deputy chair. Also what action enables/authorizes vice chair to make decisions ? Should it be explicit delegation on chair's part.

Thanks @jithine - I think it's important for the TOC meeting to have a prepared agenda and someone facilitating the meetings even if the chair is not available. 

Should the TOC chair be away for a prolonged period, the TOC would benefit from a member that the rest of the TOC trusts on the role, and whom could temporarily take over the role of chair.
In terms of decision-making, I would say that one of the responsibilities of the chair is to build consensus within the TOC, and the deputy chair could do the same in the absence of the chair.

**Comment by afrittoli** [comment]
Thank you @TracyRagan - the proposed change looks good to me.

**Comment by TracyRagan** [comment]
The TOC representatives will elect a chair and deputy chair.  The TOC representatives will elect a chair to preside over meetings, ensure minutes are taken and drive the TOC agenda with input from the TOC representatives, who will also serve as the TOC Representative.  The role of the deputy chair is to collaborate with and support the chair in all roles, including presiding over meetings, ensuring minutes are taken, and driving the TOC agenda at the request of the TOC chair.

**Comment by fdegir** [comment]
The charter updates are reviewed by LF Legal and currently with the CDF GB for review.
We will provide updates going forward.

Thanks everyone for their help with this.

**Comment by afrittoli** [comment]
@fdegir I think this item is complete now, correct?

**Comment by fdegir** [comment]
@afrittoli yes. closing it now.

The updated charter is available here: https://github.com/cdfoundation/charter/blob/main/CHARTER.md
