### ISSUE TITLE
CDFoundation Proposal for MLOps Sig

### ISSUE THREAD

**Issue by animeshsingh** [cdfoundation/toc#34]
Hi all,

I have created an initial proposal for MLOps Sig to be kickstarted as part of CDFoundation. Would like to get more members on-boarded and interest generated to move this forward for voting

https://docs.google.com/document/d/1aFLLffju7q7ksDIAAQJeKBC6yeSbDpreL2ZrQbqZ05M/edit?usp=sharing

**Comment by michaelneale** [comment]
I like the sound of this!

**Comment by aglover** [comment]
If this is a Tekton specific SIG, why not put it in Tekton's project? Or is there an opportunity to examine MLOps more broadly?

**Comment by animeshsingh** [comment]
Can be examined more boradly, but initial implementations can be driven through Tekton as a base. Depending on the interest in the group, I will PR the proposal to the right project.

**Comment by hamelsmu** [comment]
I fully support this proposal and think its a great idea.  I am on board and would like to contribute.

**Comment by michaelneale** [comment]
I would like to join and represent my org

**Comment by vincent-pli** [comment]
@animeshsingh 
I think that's a great idea.
I worked on Tekton for several months, I would like to join and contribute, thanks

**Comment by danlopez00** [comment]
I added a spot in sigs/proposed.md for MLOps, and feel free to update the desc via a pull request

https://github.com/cdfoundation/toc/blob/master/sigs/proposed.md

**Comment by animeshsingh** [comment]
All - would like to get this kickstarted now. Please leave your email ids either here, or on the Google doc so that I can identify who to include.

**Comment by michaelneale** [comment]
mneale @ cloudbees . com

**Comment by danlopez00** [comment]
When ready please create a pull request to update https://github.com/cdfoundation/toc/blob/master/sigs/proposed.md

and add a file: sig-mlops.md like https://github.com/cdfoundation/toc/blob/master/sigs/sig-security.md

Once the PR is merged, please contact the CDF team to get the repo, share drive, and mail lists established

**Comment by tequilarista** [comment]
dournov @ google . com and jlewi @ google . com are the likely participants from the Google side, but will confirm next week

**Comment by animeshsingh** [comment]
@danlopez00 I have updated the first file there. I will do a proposal file with sig-mlops.md with chairs/co-chairs listed next week. 

@tequilarista let us know once the names are finalized at your end

**Comment by animeshsingh** [comment]
@danlopez00 the two PR's are in. Please take a look, and see if we can get this accelerated.

**Comment by danlopez00** [comment]
@animeshsingh there are some conflicts with your PR. Please resolve and I can merge

**Comment by vincent-pli** [comment]
lplpli@cn.ibm.com
thanks

**Comment by animeshsingh** [comment]
@danlopez00 look at this
https://github.com/cdfoundation/toc/pull/45

**Comment by animeshsingh** [comment]
@tequilarista I have Jeremy/Pavel listed here from KFP side. Anyone from Google on core Tekton side?

**Comment by danlopez00** [comment]
@animeshsingh #45 is now merged

**Comment by MarckK** [comment]
kdelamarck @ cloudbees . com  
thank you

**Comment by danlopez00** [comment]
Proposal has been merged

**Comment by danlopez00** [comment]
Please move comms to https://lists.cd.foundation/g/sig-mlops and the #sig-mlops channel in Slack.
And repo for meetings, agenda, docs: https://github.com/cdfoundation/sig-mlops
