### ISSUE TITLE
SIG Charter and Processes

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/toc#70]
As noted in the comment to a PR in sig-interoperability, TOC don't have a document to describe  governance/operation model for SIGs to adapt. [0] The approved SIGs do not have one either.

Since CDF SIGs are overseen by CDF TOC, it could be meaningful for CDF TOC to craft a charter for its SIGs and document a (lightweight) process so SIGs can be bound by it and refer to it from their own charters in their repos.

Some of the questions that would be good to address in such document are

- objectives with the SIGs
- SIG formation process (already described in Readme file [1])
- how the SIGs are expected to operate and be governed (adheres to TOC principles, has chair/co-chair, no/term/election of chairs, decision making, etc.)
- roles and responsibilities (tech leads, etc)
- how one can become member to SIG (self-declared, voting is not required)

I think what CNCF already has is something we can simplify and adapt. [2] In fact, some of the items listed above comes straight from that document.

If people think this is something we need, I can send a PR to gather feedback. Once we think it is good, we can bring this to the TOC's attention.

[0] https://github.com/cdfoundation/sig-Interoperability/pull/1#issuecomment-574710624
[1] https://github.com/cdfoundation/toc/blob/master/sigs/README.md
[2] https://github.com/cncf/toc/blob/master/sigs/cncf-sigs.md

**Comment by tequilarista** [comment]
oh, this is a good point, thanks for raising this issue!  A very quick read of the CNCF version gives me  some thoughts on a few possible variations I'd like to propose but in principle I like the general gist of what's there.

**Comment by tequilarista** [comment]
added this to agenda of TOC meeting on 1/28/20

**Comment by danlopez00** [comment]
@tequilarista lets close this out at the next TOC meeting.

**Comment by fdegir** [comment]
I think this can be closed as I found the document which describes most of the points I was searching for.

https://github.com/cdfoundation/toc/blob/master/GROUPS.md#sigs
