### ISSUE TITLE
☀️ GSoC ideas list for CDF points to the wrong page

### ISSUE THREAD

**Issue by MarckK** [cdfoundation/toc#73]
The Continuous Delivery Foundation has been accepted as a [mentoring organisation for Google Summer of Code](https://summerofcode.withgoogle.com/organizations/5550056498790400/).   🎉

However, the 'View Ideas List' button on the [CDF mentoring org page](https://summerofcode.withgoogle.com/organizations/5550056498790400/) links to [CDF TOC Project Lifecycle information](https://github.com/cdfoundation/toc/blob/master/PROJECT_LIFECYCLE.md), which describes information for existing OSS projects that wish to join the CDF, not ideas for GSoC students.

**Comment by danlopez00** [comment]
Resolved
